###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cimeld105)
#  Generated on:      Wed Jun 15 03:20:53 2022
#  Design:            top_io
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin t_op/u_cdr/div1/cnt_div/o_en_freq_synch_reg/C 0.084
set_ccopt_property insertion_delay -pin {t_op/u_cdr/cnt_d_reg[0]/C} 0.300
set_ccopt_property insertion_delay -pin {t_op/u_cdr/cnt_d_reg[1]/C} 0.300
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[0]/C} 0.425
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[1]/C} 0.480
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[2]/C} 0.460
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[3]/C} 0.402
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[4]/C} 0.300
set_ccopt_property insertion_delay -pin {t_op/u_cdr/div1/o_nb_P_reg[5]/C} 0.388

# Clocks present at pin io_inClock/Y
#   inClock (period 20.000ns) in timing_config setup_func_mode([/calcul/zigbee_project_2/implem/pnr/PNR_TOP_ANTHO_TYP/WORK/dbs/prects_enc.dat/mmmc/modes/setup_func_mode/setup_func_mode.sdc])
#   inClock (period 20.000ns) in timing_config hold_func_mode([/calcul/zigbee_project_2/implem/pnr/PNR_TOP_ANTHO_TYP/WORK/dbs/prects_enc.dat/mmmc/modes/hold_func_mode/hold_func_mode.sdc])
create_ccopt_clock_tree -name inClock -source io_inClock/Y -no_skew_group

# Clock period setting for source pin of inClock
set_ccopt_property clock_period -pin io_inClock/Y 20

# Skew group to balance non generated clock:inClock in timing_config:setup_func_mode (sdc /calcul/zigbee_project_2/implem/pnr/PNR_TOP_ANTHO_TYP/WORK/dbs/prects_enc.dat/mmmc/modes/setup_func_mode/setup_func_mode.sdc)
create_ccopt_skew_group -name inClock/setup_func_mode -sources io_inClock/Y -auto_sinks
set_ccopt_property include_source_latency -skew_group inClock/setup_func_mode true
set_ccopt_property extracted_from_clock_name -skew_group inClock/setup_func_mode inClock
set_ccopt_property extracted_from_constraint_mode_name -skew_group inClock/setup_func_mode setup_func_mode
set_ccopt_property extracted_from_delay_corners -skew_group inClock/setup_func_mode corner_typ

# Skew group to balance non generated clock:inClock in timing_config:hold_func_mode (sdc /calcul/zigbee_project_2/implem/pnr/PNR_TOP_ANTHO_TYP/WORK/dbs/prects_enc.dat/mmmc/modes/hold_func_mode/hold_func_mode.sdc)
create_ccopt_skew_group -name inClock/hold_func_mode -sources io_inClock/Y -auto_sinks
set_ccopt_property include_source_latency -skew_group inClock/hold_func_mode true
set_ccopt_property extracted_from_clock_name -skew_group inClock/hold_func_mode inClock
set_ccopt_property extracted_from_constraint_mode_name -skew_group inClock/hold_func_mode hold_func_mode
set_ccopt_property extracted_from_delay_corners -skew_group inClock/hold_func_mode corner_min


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

