###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cimeld39.cime.inpg.fr)
#  Generated on:      Mon Jun 13 17:39:00 2022
#  Design:            top_io
#  Command:           saveDesign dbs/pnr_before_opt_design
###############################################################
current_design top_io
