###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cimeld39.cime.inpg.fr)
#  Generated on:      Mon Jun 13 19:31:35 2022
#  Design:            top_io
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
