###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cimeld105)
#  Generated on:      Wed Jun  8 09:18:59 2022
#  Design:            top_io
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
